### PR TITLE
[cs] add missing functions, some arithmetic operator overloads

### PR DESCRIPTION
**Pull request by UndeadRat22**
Added some missing external functions, static factory for commonly used values, like `Fr.One();`.  Also some overloads of arithmetic operators on G1.

### CODE REVIEW

**Comment by herumi** [comment]
Thank you for the patch.
Do you need evaluatePolynomial and LagrangeInterpolation?

**Comment by UndeadRat22** [comment]
> Thank you for the patch.
> Do you need evaluatePolynomial and LagrangeInterpolation?

Yeah, I think I will need those later on. I will create more PRs once I get to that point :).

**Comment by herumi** [comment]
Okay, I'll append them later. By the way, could you tell me what do you use them if possible?

**Comment by UndeadRat22** [comment]
I'm working on a KZG10 library in c#. After that's done I will move on to write an optimized version in rust. Will most likely use MCL there as well :).

**Comment by herumi** [comment]
I've added Fr/G1/G2 Share and Recover method.
cf. https://github.com/herumi/mcl/blob/master/ffi/cs/test/test.cs#L289

**Pull request merged**
