### PR TITLE
add G1GetBasePoint in golang api

### PR DESCRIPTION
**Pull request by levyfan**

### CODE REVIEW

**Comment by levyfan** [comment]
Hi @herumi , I add the G1GetBasePoint api to golang. Please let me known if this is OK.

**Comment by herumi** [comment]
This API is useful for only `SECP*` curve. Is it okay?

**Comment by levyfan** [comment]
I see. I need a base point for BN254.

**Comment by herumi** [comment]
I don't think that the base point of BN254 is defined. If you want to set it as a point (x, y), then use `setStr(P, "1 <x> <y>", 10)`.
https://github.com/herumi/mcl/blob/master/api.md#set-string

**Comment by levyfan** [comment]
As the curve is Y²=X³+3, I guess we can just set X=1 and Y=2?
https://github.com/ConsenSys/gnark-crypto/blob/7fcb6a36443a7c998756e3910d0d99aeb37d0213/ecc/bn254/bn254.go#L108

**Comment by herumi** [comment]
Yes. You can use`g1Gen.SetString("1 1 2", 10)`. The first `1` means Affine format string.

**Comment by herumi** [comment]
How about `MCL_BN_SNARK1`?

**Comment by levyfan** [comment]
ok get that~

**Pull request closed without merging**
